CREATE TABLE tarefas(
    ID BIGSERIAL PRIMARY KEY,
    ID_USUARIO BIGSERIAL,
    NOME VARCHAR(255),
    TITULO VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT NOW()
);